[admin-feature] course management APIs
panda1835/Fulbright_SoftwareEngineering_FinalProject pull request #10
Opened 2020-10-05 22:00 UTC by anh-nguyen-98

Success with spring-boot app and basic tests on Postman

2020-10-05 22:36 UTC, anh-nguyen-98 commented
Any disadvantages using 
```java 
@Entity
public class Course{
     ....
    @ElementCollection
    @CollectionTable(name = "professors")
    private List<String> professors; // prof name

     ....
    @ElementCollection
    @CollectionTable(name = "prerequisites")
    private List<String> prerequisites; // courseId

}
```
?

2020-10-07 06:37 UTC, panda1835 requested changes

2020-10-07 06:37 UTC, panda1835 commented on course-registration/src/main/java/com/se2020/course/registration/entity/User.java
> +    public User(String email, String password){
I think the constructor should also have the userId

2020-10-07 06:37 UTC, panda1835 commented on course-registration/src/main/java/com/se2020/course/registration/controller/UserController.java
> +        userRepository.save(user);
Does this save() update the row or add a new row? I am afraid it is the latter case. I think you should add this line
` User user = userRepository.getOne(user.getId());`
below `User user = userRepository.findByUserId(userId).get();`

2020-10-07 06:37 UTC, panda1835 commented on course-registration/src/main/java/com/se2020/course/registration/controller/UserController.java
> +        Course course = courseRepository.findByCourseId(courseId).get();
Same concern for update Student, I think you should use getOne()

2020-10-07 06:37 UTC, panda1835 commented on course-registration/src/main/java/com/se2020/course/registration/controller/UserController.java
> +
Where is the save()?

2020-10-07 06:37 UTC, panda1835 commented on course-registration/src/main/java/com/se2020/course/registration/enums/PermissionsEnum.java
> +    LOG_IN, CHANGE_PASSWORD, MODIFY_PROFILE,
It should be nice if you can name the enums so that it is distinguishable for student, admin and guest user. For example STUDENT_REGISTER_COURSE, ADMIN_ADD_USER

2020-10-07 06:37 UTC, panda1835 commented on course-registration/src/main/java/com/se2020/course/registration/utils/RoleUtils.java
> +import com.se2020.course.registration.enums.PermissionsEnum;
is it cleaner to call the enum with
`import com.se2020.course.registration.enums.PermissionsEnum.*`

2020-10-07 08:36 UTC, anh-nguyen-98 commented on course-registration/src/main/java/com/se2020/course/registration/controller/UserController.java
> +        userRepository.save(user);
I reviewed on Postman -- the original code updates the row (without adding a new row)

2020-10-07 08:37 UTC, anh-nguyen-98 commented on course-registration/src/main/java/com/se2020/course/registration/controller/UserController.java
> +        Course course = courseRepository.findByCourseId(courseId).get();
I reviewed on Postman -- the original code updates the row (without adding a new row)

2020-10-07 08:37 UTC, anh-nguyen-98 commented on course-registration/src/main/java/com/se2020/course/registration/controller/UserController.java
> +
bug fixed

2020-10-07 08:41 UTC, anh-nguyen-98 commented on course-registration/src/main/java/com/se2020/course/registration/entity/User.java
> +    public User(String email, String password){
bug fixed

2020-10-07 08:49 UTC, anh-nguyen-98 commented on course-registration/src/main/java/com/se2020/course/registration/enums/PermissionsEnum.java
> +    LOG_IN, CHANGE_PASSWORD, MODIFY_PROFILE,
some permissions (e.g. GET_COURSE -- view all courses in system) apply to many roles

2020-10-07 09:30 UTC, panda1835 approved these changes

2020-10-07 09:37 UTC, merged